package com.hms.infrastructure.persistence.gst;

import com.hms.domain.gst.model.GstFilingRecord;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;
import java.util.UUID;

public interface GstFilingRecordJpaRepository extends JpaRepository<GstFilingRecord, UUID> {

    @Query("SELECT r FROM GstFilingRecord r WHERE r.status <> 2 ORDER BY r.createdAt DESC")
    List<GstFilingRecord> findHistory();

    /** Previous scheduler output for a period — superseded before a new run is stored. */
    @Query("SELECT r FROM GstFilingRecord r WHERE r.tenantId = :tenantId " +
           "AND r.returnType = :type AND r.returnPeriod = :period " +
           "AND r.autoGenerated = TRUE AND r.status <> 2")
    List<GstFilingRecord> findAutoGenerated(@Param("tenantId") UUID tenantId,
                                            @Param("type") com.hms.domain.gst.model.GstReturnType type,
                                            @Param("period") String period);

    @Query("SELECT r FROM GstFilingRecord r WHERE r.returnType = :type " +
           "AND r.returnPeriod = :period AND r.status <> 2 ORDER BY r.createdAt DESC")
    List<GstFilingRecord> findByPeriod(@Param("type") com.hms.domain.gst.model.GstReturnType type,
                                       @Param("period") String period);
}
