package com.hms.application.gst;

import com.hms.application.report.modules.GstReportDataService;
import com.hms.domain.gst.model.*;
import com.hms.exception.BusinessRuleViolationException;
import com.hms.exception.ResourceNotFoundException;
import com.hms.infrastructure.persistence.gst.GstFilingRecordJpaRepository;
import com.hms.infrastructure.persistence.payor.PayorJpaRepository;
import com.hms.infrastructure.tenant.TenantContext;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

/**
 * Generates, records and (where a hospital has wired a GSP) submits GST returns.
 *
 * <p>This is a <b>provision</b>, not an integration. It builds a complete, validated
 * payload and keeps a durable record of it; what it deliberately does not do is ship a
 * client for any particular GST Suvidha Provider. Hospitals connect their own, and until
 * one is configured the useful path is {@link #generate} followed by downloading the
 * JSON and uploading it to the GST portal — which is how most hospitals will file.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class GstFilingService {

    private final GstReportDataService gstReportDataService;
    private final GstConfigurationService configService;
    private final GstPayloadBuilder payloadBuilder;
    private final GstFilingRecordJpaRepository filingRepo;
    private final PayorJpaRepository payorRepo;

    private static final DateTimeFormatter RETURN_PERIOD = DateTimeFormatter.ofPattern("MMyyyy");

    /**
     * Builds a return for one month and stores it (A2, A3, A6).
     *
     * <p>Each call creates a new record rather than replacing the previous one for that
     * period. Back-dated bills change a period's figures after the fact, and overwriting
     * would destroy the evidence of what the return said when it was filed.
     */
    @Transactional
    public GstFilingRecord generate(GstReturnType returnType, YearMonth period) {
        return generate(returnType, period, false);
    }

    /**
     * @param autoGenerated when true, supersedes the scheduler's own previous output for
     *                      this period instead of stacking another draft beside it
     */
    @Transactional
    public GstFilingRecord generate(GstReturnType returnType, YearMonth period, boolean autoGenerated) {
        if (returnType == null) throw new BusinessRuleViolationException("Return type is required");
        if (period == null)     throw new BusinessRuleViolationException("Return period is required");

        GstConfiguration config = configService.getForCurrentTenant();
        LocalDate start = period.atDay(1);
        LocalDate end   = period.atEndOfMonth();

        List<Map<String, Object>> rows =
            gstReportDataService.getFilingLines(start.toString(), end.toString());

        String homeState = config.getStateCode();
        List<GstPayloadBuilder.Supply> supplies =
            payloadBuilder.toSupplies(rows, homeState, resolvePayors(rows));

        String returnPeriod = period.format(RETURN_PERIOD);
        String payload = returnType == GstReturnType.GSTR1
            ? payloadBuilder.buildGstr1(supplies, config.getGstin(), returnPeriod)
            : payloadBuilder.buildGstr3b(supplies, config.getGstin(), returnPeriod);

        GstFilingRecord record = new GstFilingRecord();
        record.setTenantId(TenantContext.require());
        record.setReturnType(returnType);
        record.setReturnPeriod(returnPeriod);
        record.setPeriodStart(start);
        record.setPeriodEnd(end);
        record.setEnvironment(config.getActiveEnvironment());
        record.setGstin(config.getGstin());
        record.setPayload(payload);
        record.setAutoGenerated(autoGenerated);

        record.setTotalTaxableValue(total(supplies, GstPayloadBuilder.Supply::taxableValue));
        record.setTotalCgst(total(supplies, GstPayloadBuilder.Supply::cgst));
        record.setTotalSgst(total(supplies, GstPayloadBuilder.Supply::sgst));
        record.setTotalIgst(total(supplies, GstPayloadBuilder.Supply::igst));
        record.setTotalCess(BigDecimal.ZERO);
        record.setLineItemCount(supplies.size());

        payloadBuilder.toLineItems(supplies).forEach(record::addLineItem);

        List<GstFilingError> errors =
            payloadBuilder.validate(supplies, config.getGstin(), homeState);
        errors.forEach(record::addError);

        // A return with known problems is still worth keeping — the hospital needs to see
        // the payload alongside what is wrong with it — but it is not GENERATED, because
        // GENERATED is what the "File GST" action is allowed to act on.
        record.setFilingStatus(errors.isEmpty() ? GstFilingStatus.GENERATED : GstFilingStatus.ERROR);

        if (autoGenerated) {
            // Retire the previous scheduled run for this period. Manual generations are
            // never touched — a person's return is evidence, not a cache entry.
            filingRepo.findAutoGenerated(record.getTenantId(), returnType, returnPeriod)
                .forEach(prev -> {
                    prev.setStatus(com.hms.domain.shared.model.EntityStatus.DELETED);
                    filingRepo.save(prev);
                });
        }

        GstFilingRecord saved = filingRepo.save(record);
        log.info("GST {} generated for tenant {} period {} — {} lines, {} validation errors",
            returnType, saved.getTenantId(), returnPeriod, supplies.size(), errors.size());
        return saved;
    }


    /**
     * Recipient details for every payor referenced in the period.
     *
     * <p>Loaded through JPA rather than read in the filing SQL because a payor's GSTIN is
     * encrypted at rest: the entity converter decrypts it, whereas the raw JDBC the report
     * queries use would hand back ciphertext and quietly put it in the return.
     */
    private Map<UUID, GstPayloadBuilder.Recipient> resolvePayors(List<Map<String, Object>> rows) {
        Set<UUID> payorIds = rows.stream()
            .map(r -> r.get("payor_id"))
            .filter(UUID.class::isInstance)
            .map(UUID.class::cast)
            .collect(java.util.stream.Collectors.toSet());
        if (payorIds.isEmpty()) return Map.of();

        Map<UUID, GstPayloadBuilder.Recipient> resolved = new java.util.HashMap<>();
        payorRepo.findAllById(payorIds).forEach(p -> resolved.put(
            p.getId(), new GstPayloadBuilder.Recipient(p.getGstin(), p.getStateCode())));
        return resolved;
    }

    @Transactional(readOnly = true)
    public List<GstFilingRecord> history() {
        return filingRepo.findHistory();
    }

    @Transactional(readOnly = true)
    public GstFilingRecord get(UUID id) {
        return filingRepo.findById(id)
            .orElseThrow(() -> new ResourceNotFoundException("GST filing record", id));
    }

    /** A4 — the payload as the hospital would upload it to the GST portal. */
    @Transactional(readOnly = true)
    public String payloadOf(UUID id) {
        String payload = get(id).getPayload();
        if (payload == null || payload.isBlank()) {
            throw new BusinessRuleViolationException("This filing has no payload to download");
        }
        return payload;
    }

    /**
     * A5 — the submission trigger.
     *
     * <p>No GSP client ships with this module, so the call fails loudly rather than
     * pretending. Everything up to the moment of transmission is real and exercised: the
     * record, the payload, the validation, the status transitions and the audit trail. A
     * hospital wiring its own provider implements the transport here and nothing else
     * needs to change.
     */
    @Transactional
    public GstFilingRecord submit(UUID id) {
        GstFilingRecord record = get(id);
        GstConfiguration config = configService.getForCurrentTenant();

        if (!config.isIntegrationEnabled()) {
            throw new BusinessRuleViolationException(
                "GST integration is not enabled for this hospital. Download the JSON and file "
                + "it through the GST portal, or ask a platform administrator to enable it.");
        }
        if (record.getFilingStatus() == GstFilingStatus.ERROR) {
            throw new BusinessRuleViolationException(
                "This return has validation errors. Fix them and generate it again before filing.");
        }
        if (record.getFilingStatus() == GstFilingStatus.FILED) {
            throw new BusinessRuleViolationException("This return has already been filed.");
        }
        if (!config.isSubmittable()) {
            throw new BusinessRuleViolationException(
                "GST credentials or endpoint are incomplete. Complete them under Settings → GST.");
        }

        throw new BusinessRuleViolationException(
            "No GST Suvidha Provider is connected. This build generates and validates returns "
            + "but does not transmit them — download the JSON and file it through the portal.");
    }

    private BigDecimal total(List<GstPayloadBuilder.Supply> supplies,
                             java.util.function.Function<GstPayloadBuilder.Supply, BigDecimal> field) {
        return supplies.stream()
            .map(field)
            .reduce(BigDecimal.ZERO, BigDecimal::add)
            .setScale(2, java.math.RoundingMode.HALF_UP);
    }
}
