package com.hms.application.claims;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.hms.application.policy.PolicyDiscoveryService;
import com.hms.infrastructure.persistence.preauth.PreAuthEnhancementJpaRepository;
import com.hms.infrastructure.nhcx.NhcxPayloadCodec;
import com.hms.infrastructure.tenant.BranchContext;
import com.hms.infrastructure.tenant.TenantContext;
import com.hms.infrastructure.persistence.nhcx.NhcxTransactionEntity;
import com.hms.infrastructure.persistence.nhcx.NhcxTransactionJpaRepository;
import io.micrometer.core.instrument.MeterRegistry;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * Processes a verified payer response.
 *
 * <p>Runs outside any tenant context: the callback arrives from NHCX with no
 * session, so the correlation id is what identifies the tenant. It is looked up
 * without a tenant filter and the tenant is then read from the stored
 * transaction — which is safe because the correlation id was generated by us and
 * the payload's signature has already been verified by the caller.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class NhcxCallbackService {

    private final NhcxPayloadCodec codec;
    private final NhcxTransactionJpaRepository repository;
    private final ObjectMapper objectMapper;
    private final MeterRegistry meterRegistry;
    private final PolicyDiscoveryService coverage;
    private final ClaimPaymentService payments;
    private final PreAuthService preAuth;
    private final PreAuthEnhancementJpaRepository enhancements;

    /**
     * @throws com.hms.infrastructure.gov.GovApiException if the signature does
     *         not verify. An unverified callback is not acted on.
     */
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void handle(String jwePayload, String correlationId, String senderCode) {
        // Verification first. Everything below trusts this call's result.
        String json = codec.decryptAndVerify(jwePayload);

        Optional<NhcxTransactionEntity> found = repository.findByCorrelationId(correlationId);
        if (found.isEmpty()) {
            // Either a callback for a submission we never made, or one that
            // arrived before our own commit. Worth an alert either way.
            log.error("nhcx.callback.unknown_correlation correlationId[{}] sender[{}]",
                      correlationId, senderCode);
            meterRegistry.counter("hms_nhcx_callbacks_total",
                                  "outcome", "unknown_correlation").increment();
            return;
        }

        NhcxTransactionEntity txn = found.get();

        // Establish tenant context from the resolved transaction before touching
        // anything. Saving would in fact survive without it — assertScopeMatches
        // is a no-op when the active tenant is null, and the stored tenantId is
        // preserved on update — but relying on that is relying on an accident.
        // Anything this triggers downstream (listeners, notifications, audit)
        // needs a real tenant, and setting it explicitly is the pattern used by
        // BulkImportAsyncService for exactly this reason.
        TenantContext.set(txn.getTenantId());
        BranchContext.set(txn.getBranchId());
        try {
            process(txn, json, correlationId);
        } finally {
            TenantContext.clear();
            BranchContext.clear();
        }
    }

    private void process(NhcxTransactionEntity txn, String json, String correlationId) {
        // Callbacks are at-least-once. A duplicate must not overwrite a decided
        // claim or re-trigger downstream work.
        if (!txn.isAwaitingCallback()) {
            log.info("nhcx.callback.duplicate correlationId[{}] state[{}]",
                     correlationId, txn.getState());
            meterRegistry.counter("hms_nhcx_callbacks_total",
                                  "outcome", "duplicate").increment();
            return;
        }

        try {
            JsonNode root = objectMapper.readTree(json);
            String outcome = extractOutcome(root);
            txn.setState(mapState(outcome));
            txn.setOutcomeCode(outcome);
            txn.setApprovedAmount(extractApprovedAmount(root));
            txn.setResponsePayload(json);   // encrypted at rest by the converter
            txn.setRespondedAt(Instant.now());
            repository.save(txn);

            // Dispatch to the handler this payload belongs to.
            //
            // Deliberately after the transaction is saved and deliberately
            // non-fatal per branch: a payer sending detail we cannot parse must
            // not discard the decision just recorded. Each failure is counted
            // with its route, because a handler that silently never runs is the
            // failure mode this whole indirection exists to make visible.
            dispatch(txn, root, correlationId, outcome);

            long seconds = txn.getSubmittedAt() == null ? 0
                : Duration.between(txn.getSubmittedAt(), Instant.now()).getSeconds();
            meterRegistry.timer("hms_nhcx_callback_latency_seconds")
                .record(Duration.ofSeconds(Math.max(seconds, 0)));
            meterRegistry.counter("hms_nhcx_callbacks_total",
                                  "outcome", txn.getState()).increment();

            // Ids and the decision only. The bundle is clinical detail.
            log.info("nhcx.callback.processed correlationId[{}] state[{}] latencySeconds[{}]",
                     correlationId, txn.getState(), seconds);

        } catch (Exception e) {
            txn.setState("FAILED");
            txn.setOutcomeCode("RESPONSE_UNREADABLE");
            txn.setRespondedAt(Instant.now());
            repository.save(txn);
            log.error("nhcx.callback.unreadable correlationId[{}] type[{}]",
                      correlationId, e.getClass().getSimpleName());
        }
    }

    /**
     * Route a verified callback to the service that owns it.
     *
     * <p>Routing lives in {@link NhcxCallbackRouter}, which is dependency-free
     * and separately executed. The decision matters more than it looks: a
     * PaymentNotice arrives on the <em>claim</em> exchange, so dispatching on
     * exchange type alone would file a disbursal as a claim outcome and the UTR
     * would never reach reconciliation — the money would stop being tracked
     * with nothing in the logs to say so.
     */
    private void dispatch(NhcxTransactionEntity txn, JsonNode root, String correlationId,
                          String outcome) {

        boolean isEnhancement = enhancements.findByCorrelationId(correlationId).isPresent();
        String resourceType = root.path("resourceType").asText(null);

        NhcxCallbackRouter.Route route =
            NhcxCallbackRouter.resolve(txn.getExchangeType(), resourceType, isEnhancement);

        if (route == NhcxCallbackRouter.Route.NONE) {
            // Not an error. Recognised transport with nothing to hand on — but
            // counted, so a payload type we have never seen shows up as a spike
            // rather than as silence.
            meterRegistry.counter("hms_nhcx_callbacks_total", "outcome", "no_route").increment();
            log.info("nhcx.callback.no_route correlationId[{}] exchange[{}] resource[{}]",
                     correlationId, txn.getExchangeType(), resourceType);
            return;
        }

        try {
            switch (route) {
                case COVERAGE -> coverage.applyCoverageResponse(correlationId, root);

                case PAYMENT_NOTICE -> payments.recordPaymentAdvice(correlationId, root);

                case PREAUTH_OUTCOME -> {
                    // A query is not a rejection. Closing a pre-auth the insurer
                    // is still considering makes the hospital resubmit instead
                    // of answering, restarting the clock on an admitted patient.
                    if (NhcxCallbackRouter.isQuery(outcome)) {
                        preAuth.recordQuery(correlationId, outcome, extractQueryText(root));
                    }
                }

                case ENHANCEMENT_OUTCOME -> preAuth.recordEnhancementOutcome(
                    correlationId,
                    NhcxCallbackRouter.isQuery(outcome) ? "QUERY_RAISED" : mapState(outcome),
                    txn.getApprovedAmount());

                case CLAIM_OUTCOME -> {
                    // The exchange result is already on the row; the financial
                    // lifecycle only advances when a PaymentNotice arrives.
                    txn.setFinancialState(
                        ClaimSettlementCalculator.financialState(
                            "APPROVED".equals(txn.getState()), false, false, false));
                    repository.save(txn);
                }

                default -> { }
            }

            meterRegistry.counter("hms_nhcx_dispatch_total",
                                  "route", route.name(), "outcome", "ok").increment();

        } catch (RuntimeException e) {
            meterRegistry.counter("hms_nhcx_dispatch_total",
                                  "route", route.name(), "outcome", "failed").increment();
            log.error("nhcx.callback.dispatch_failed route[{}] correlationId[{}] type[{}]",
                      route, correlationId, e.getClass().getSimpleName());
        }
    }

    /**
     * Pull the insurer's question out of a query response.
     *
     * <p>Falls back to the outcome code rather than leaving it blank: a query
     * row with no text tells the desk something is wanted without saying what,
     * which is worse than a terse code they can look up.
     */
    private String extractQueryText(JsonNode root) {
        for (JsonNode error : root.path("error")) {
            String text = error.path("code").path("coding").path(0).path("display").asText(null);
            if (text != null && !text.isBlank()) {
                return text;
            }
        }
        String disposition = root.path("disposition").asText(null);
        return disposition == null || disposition.isBlank()
            ? "The insurer raised a query. See the payer portal for detail."
            : disposition;
    }

    /**
     * Escalate submissions the payer never answered.
     *
     * <p>Scheduled, so no tenant context — the query is time-based and spans
     * tenants deliberately. Without this a claim sits in limbo indefinitely and
     * the hospital is unpaid and unaware, which is the failure this whole
     * asynchronous flow is most prone to.
     */
    @org.springframework.scheduling.annotation.Scheduled(fixedDelayString = "PT10M")
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void expireStalled() {
        try {
            List<NhcxTransactionEntity> stalled = repository.findStalled(Instant.now());
            for (NhcxTransactionEntity txn : stalled) {
                txn.setState("TIMED_OUT");
                txn.setOutcomeCode("NO_PAYER_RESPONSE");
                repository.save(txn);
                meterRegistry.counter("hms_nhcx_timeouts_total",
                                      "type", txn.getExchangeType()).increment();
                log.error("nhcx.timed_out correlationId[{}] type[{}] payer[{}] "
                          + "- no payer response; needs manual follow-up",
                          txn.getCorrelationId(), txn.getExchangeType(), txn.getPayerCode());
            }
        } catch (RuntimeException e) {
            log.error("nhcx.expiry.failed type[{}]", e.getClass().getSimpleName());
        }
    }

    private String extractOutcome(JsonNode root) {
        // FHIR puts the decision on the response resource inside the bundle.
        for (JsonNode entry : root.path("entry")) {
            JsonNode resource = entry.path("resource");
            String type = resource.path("resourceType").asText("");
            if (type.equals("ClaimResponse") || type.equals("CoverageEligibilityResponse")) {
                String outcome = resource.path("outcome").asText("");
                if (!outcome.isBlank()) {
                    return outcome;
                }
            }
        }
        return "unknown";
    }

    private Long extractApprovedAmount(JsonNode root) {
        for (JsonNode entry : root.path("entry")) {
            JsonNode resource = entry.path("resource");
            if (!"ClaimResponse".equals(resource.path("resourceType").asText(""))) {
                continue;
            }
            for (JsonNode total : resource.path("total")) {
                JsonNode amount = total.path("amount").path("value");
                if (!amount.isMissingNode()) {
                    // FHIR Money is decimal; the ledger holds integer minor units.
                    return Math.round(amount.asDouble() * 100);
                }
            }
        }
        return null;
    }

    private String mapState(String outcome) {
        return switch (outcome.toLowerCase(java.util.Locale.ROOT)) {
            case "complete", "approved" -> "APPROVED";
            case "error", "rejected", "denied" -> "REJECTED";
            case "partial" -> "APPROVED";
            default -> "ACKNOWLEDGED";
        };
    }
}
