-- V063__add_contact_person_to_payors_and_seed_permissions.sql
-- Add missing contact_person column to payors table (in case V033 was skipped due to local database version conflicts)
ALTER TABLE payors ADD COLUMN IF NOT EXISTS contact_person VARCHAR(100);

-- Seed remaining features from V059 (in case V059 was skipped due to local database version conflicts)
-- 1. Insert Features
INSERT INTO features (id, feature_key, module, description) VALUES
    (gen_random_uuid(), 'REGISTRATION', 'RECEPTION', 'Access Patient Registration'),
    (gen_random_uuid(), 'OP_BILLING', 'BILLING', 'Access Outpatient Billing'),
    (gen_random_uuid(), 'IP_BILLING', 'BILLING', 'Access Inpatient Billing'),
    (gen_random_uuid(), 'PAYMENT', 'BILLING', 'Access Payments'),
    (gen_random_uuid(), 'SPECIAL_COLLECTION', 'DIAGNOSTICS', 'Access Special Collections'),
    (gen_random_uuid(), 'LAB_REPORT', 'DIAGNOSTICS', 'Access Lab Reports'),
    (gen_random_uuid(), 'IP_AUTOMATED_ORDERS', 'CLINICAL', 'Automated IP Orders'),
    (gen_random_uuid(), 'IP_AUTOMATED_BED', 'CLINICAL', 'Automated IP Beds'),
    (gen_random_uuid(), 'IP_AUTOMATED_OTHER_CHARGE', 'BILLING', 'Automated IP Other Charges'),
    (gen_random_uuid(), 'REPORTS', 'REPORTS', 'Access Reports'),
    (gen_random_uuid(), 'PATIENT_SEARCH', 'RECEPTION', 'Search Patients'),
    (gen_random_uuid(), 'SETTINGS_REFERRAL', 'SETTINGS', 'Referrals Settings'),
    (gen_random_uuid(), 'SETTINGS_CHARGES', 'SETTINGS', 'Charges Settings'),
    (gen_random_uuid(), 'SETTINGS_PREFIX', 'SETTINGS', 'Prefix Configuration'),
    (gen_random_uuid(), 'SETTINGS_PAYERTYPE', 'SETTINGS', 'Payer Type Configuration'),
    (gen_random_uuid(), 'SETTINGS_RESULTTEMPLATE', 'SETTINGS', 'Result Templates'),
    (gen_random_uuid(), 'SETTINGS_TIMESLOTS', 'SETTINGS', 'Timeslots Settings'),
    (gen_random_uuid(), 'SETTINGS_BULKUPLOAD', 'SETTINGS', 'Bulk Upload Settings'),
    (gen_random_uuid(), 'SETTINGS_HOSPITALPROFILE', 'SETTINGS', 'Hospital Profile Settings'),
    (gen_random_uuid(), 'SETTINGS_DATAQUERY', 'SETTINGS', 'Data Query Settings'),
    (gen_random_uuid(), 'PATIENT_EDIT', 'RECEPTION', 'Edit Patients'),
    (gen_random_uuid(), 'SETTINGS_CONSULTANT_REVENUESHARE', 'SETTINGS', 'Consultant Revenue Share Settings'),
    (gen_random_uuid(), 'SETTINGS_ACCOUNTUNIT', 'SETTINGS', 'Account Unit Settings'),
    (gen_random_uuid(), 'SETTINGS_PRINTTEMPLATE', 'SETTINGS', 'Print Templates Settings'),
    (gen_random_uuid(), 'SETTINGS_AREA', 'SETTINGS', 'Area Settings'),
    (gen_random_uuid(), 'SETTINGS_MESSAGETEMPLATE', 'SETTINGS', 'Message Templates Settings'),
    (gen_random_uuid(), 'MARKETING', 'MARKETING', 'Access Marketing Module'),
    (gen_random_uuid(), 'RADIOLOGY', 'DIAGNOSTICS', 'Access Radiology Module'),
    (gen_random_uuid(), 'SETTINGS_FREQUENCY', 'SETTINGS', 'Frequency Settings'),
    (gen_random_uuid(), 'SETTINGS_TEMPLATE', 'SETTINGS', 'Template Settings'),
    (gen_random_uuid(), 'SETTINGS_BED', 'SETTINGS', 'Bed Configuration'),
    (gen_random_uuid(), 'SETTINGS_BEDTYPE', 'SETTINGS', 'Bed Type Configuration'),
    (gen_random_uuid(), 'BEDMANAGEMENT', 'CLINICAL', 'Access Bed Management'),
    (gen_random_uuid(), 'SETTINGS_SPECIMEN', 'SETTINGS', 'Specimen Settings'),
    (gen_random_uuid(), 'MEDICAL_RECORD', 'MRD', 'Access Medical Records'),
    (gen_random_uuid(), 'PATIENT_PROFILE', 'RECEPTION', 'Access Patient Profile'),
    (gen_random_uuid(), 'REPORTS_DIAGNOSTICS', 'REPORTS', 'Diagnostics Reports'),
    (gen_random_uuid(), 'REPORTS_BILLS', 'REPORTS', 'Billing Reports'),
    (gen_random_uuid(), 'REPORTS_COLLECTIONS', 'REPORTS', 'Collections Reports'),
    (gen_random_uuid(), 'REPORTS_PATIENTS', 'REPORTS', 'Patients Reports'),
    (gen_random_uuid(), 'REPORTS_ACCOUNTS', 'REPORTS', 'Accounts Reports'),
    (gen_random_uuid(), 'REPORTS_REVENUE', 'REPORTS', 'Revenue Reports'),
    (gen_random_uuid(), 'APPOINTMENT_BOOK', 'CLINICAL', 'Access Appointment Book'),
    (gen_random_uuid(), 'REPORTS_INPATIENT', 'REPORTS', 'Inpatient Reports'),
    (gen_random_uuid(), 'CHECKIN', 'RECEPTION', 'Access Checkin'),
    (gen_random_uuid(), 'SETTINGS_CONFIGURATION', 'SETTINGS', 'General Configuration'),
    (gen_random_uuid(), 'SETTINGS_CATEGORY', 'SETTINGS', 'Category Configuration'),
    (gen_random_uuid(), 'UNBILLED_DIAGNOSTIC_ORDERS', 'DIAGNOSTICS', 'Unbilled Diagnostic Orders'),
    (gen_random_uuid(), 'TALLY_REPORTS', 'REPORTS', 'Tally Reports'),
    (gen_random_uuid(), 'SALES', 'INVENTORY', 'Access Inventory Sales'),
    (gen_random_uuid(), 'PURCHASE_ORDER', 'INVENTORY', 'Access Purchase Orders'),
    (gen_random_uuid(), 'STOCK_CONSUMPTION', 'INVENTORY', 'Access Stock Consumption'),
    (gen_random_uuid(), 'REPORTS_PURCHASE', 'REPORTS', 'Purchase Reports'),
    (gen_random_uuid(), 'REPORTS_STOCK', 'REPORTS', 'Stock Reports'),
    (gen_random_uuid(), 'REPORTS_INVENTORY_ANALYSIS', 'REPORTS', 'Inventory Analysis Reports'),
    (gen_random_uuid(), 'SETTINGS_SUPPLIER', 'SETTINGS', 'Supplier Settings'),
    (gen_random_uuid(), 'SETTINGS_USER_CONFIGURATION', 'SETTINGS', 'User Configuration Settings'),
    (gen_random_uuid(), 'PATIENT_PRINT', 'RECEPTION', 'Print Patient Details'),
    (gen_random_uuid(), 'UPDATE_CLINICAL_TRAIL', 'CLINICAL', 'Update Clinical Trail'),
    (gen_random_uuid(), 'SETTINGS_CONFIG', 'SETTINGS', 'System Config Settings'),
    (gen_random_uuid(), 'SETTINGS_PRESET', 'SETTINGS', 'Preset Configuration'),
    (gen_random_uuid(), 'SETTINGS_TAX', 'SETTINGS', 'Tax Settings'),
    (gen_random_uuid(), 'OT_SCHEDULE', 'OTSCHEDULE', 'Access OT Schedule'),
    (gen_random_uuid(), 'SETTINGS_OPERATION_THEATER', 'SETTINGS', 'Operation Theater Settings'),
    (gen_random_uuid(), 'REPORTS_CLINICAL_ANALYTICS', 'REPORTS', 'Clinical Analytics Reports'),
    (gen_random_uuid(), 'PATIENT_ALLERGY', 'CLINICAL', 'Access Patient Allergies'),
    (gen_random_uuid(), 'SETTINGS_STAFF', 'SETTINGS', 'Staff Settings'),
    (gen_random_uuid(), 'REPORTS_SALES', 'REPORTS', 'Sales Reports'),
    (gen_random_uuid(), 'STOCK_INDENT', 'INVENTORY', 'Access Stock Indents'),
    (gen_random_uuid(), 'STOCK_ISSUE', 'INVENTORY', 'Access Stock Issues'),
    (gen_random_uuid(), 'STOCK_RETURN', 'INVENTORY', 'Access Stock Returns'),
    (gen_random_uuid(), 'STOCK_ADJUSTMENT', 'INVENTORY', 'Access Stock Adjustments'),
    (gen_random_uuid(), 'MRD_MANAGEMENT', 'MRD', 'Access MRD Management'),
    (gen_random_uuid(), 'REPORTS_MRD', 'REPORTS', 'MRD Reports'),
    (gen_random_uuid(), 'INSURANCE', 'INSURANCE', 'Access Insurance Module'),
    (gen_random_uuid(), 'REPORTS_INSURANCE', 'REPORTS', 'Insurance Reports'),
    (gen_random_uuid(), 'DISCHARGE_SUMMARY_ONLY', 'CLINICAL', 'Discharge Summary Access'),
    (gen_random_uuid(), 'OP_PACKAGE', 'BILLING', 'Access OP Packages'),
    (gen_random_uuid(), 'IP_PACKAGE', 'BILLING', 'Access IP Packages'),
    (gen_random_uuid(), 'MRD_REQUEST', 'MRD', 'Access MRD Requests'),
    (gen_random_uuid(), 'DONORS', 'BLOODBANK', 'Access Donors'),
    (gen_random_uuid(), 'DONOR_BLEEDING', 'BLOODBANK', 'Access Donor Bleeding'),
    (gen_random_uuid(), 'TRANSFUSION', 'BLOODBANK', 'Access Blood Transfusion'),
    (gen_random_uuid(), 'BLOOD_STOCK', 'BLOODBANK', 'Access Blood Stock'),
    (gen_random_uuid(), 'BLOOD_BANK', 'BLOODBANK', 'Access Blood Bank'),
    (gen_random_uuid(), 'REPORTS_BLOOD_BANK', 'REPORTS', 'Blood Bank Reports'),
    (gen_random_uuid(), 'SETTINGS_MOLECULE', 'SETTINGS', 'Molecule Settings'),
    (gen_random_uuid(), 'SETTINGS_FAVORITES', 'SETTINGS', 'Favorites Configuration'),
    (gen_random_uuid(), 'REPORTS_OT', 'REPORTS', 'OT Reports'),
    (gen_random_uuid(), 'AMBULANCE', 'AMBULANCE', 'Access Ambulance Module'),
    (gen_random_uuid(), 'SETTINGS_VEHICLE', 'SETTINGS', 'Vehicle Settings'),
    (gen_random_uuid(), 'SETTINGS_INSTRUMENT', 'SETTINGS', 'Instrument Settings'),
    (gen_random_uuid(), 'SETTNGS_INSTRUMENTSET', 'SETTINGS', 'Instrument Set Settings'),
    (gen_random_uuid(), 'REPORTS_AMBULANCE', 'REPORTS', 'Ambulance Reports'),
    (gen_random_uuid(), 'EQUIPMENT', 'EQUIPMENT', 'Access Equipment Module'),
    (gen_random_uuid(), 'SETTINGS_EQUIPMENT', 'SETTINGS', 'Equipment Settings'),
    (gen_random_uuid(), 'REPORTS_EQUIPMENT', 'REPORTS', 'Equipment Reports'),
    (gen_random_uuid(), 'REPORTS_CSSD', 'REPORTS', 'CSSD Reports'),
    (gen_random_uuid(), 'CSSD', 'CSSD', 'Access CSSD Module'),
    (gen_random_uuid(), 'SETTINGS_ADDITIONAL_INFO_TEMPLATE', 'SETTINGS', 'Additional Info Templates'),
    (gen_random_uuid(), 'ADMISSION_REQUEST', 'CLINICAL', 'Access Admission Requests')
ON CONFLICT (feature_key) DO NOTHING;

-- 2. Link all features to ADMIN role
INSERT INTO role_features (role_id, feature_id)
SELECT r.id, f.id 
FROM roles r, features f
WHERE r.name = 'ADMIN'
ON CONFLICT DO NOTHING;
