-- V103__delete_unused_permissions.sql
-- Delete unused, duplicate, and obsolete permission keys from the database (role grants and features)

DELETE FROM role_features WHERE feature_id IN (
    SELECT id FROM features WHERE feature_key IN (
        -- First list of 18 deleted permission keys
        'SETTINGS_SMS_TEMPLATE', 'SETTINGS_UOM', 'SETTINGS_AREA', 'SETTINGS_ACCOUNTUNIT',
        'REPORTS_OT', 'SETTINGS_VEHICLE', 'REPORTS_CSSD', 'CSSD', 'REPORTS_AMBULANCE',
        'SETTINGS_EQUIPMENT', 'AMBULANCE', 'SETTINGS_MOLECULE', 'BLOOD_STOCK',
        'DONOR_BLEEDING', 'IP_PACKAGE', 'REPORTS_BLOOD_BANK', 'STOCK_INDENT',
        'SETTINGS_OPERATION_THEATER',

        -- Second list of duplicate and obsolete permission keys
        'PATIENT_BILLS', 'PAYMENT', 'SPECIAL_COLLECTION', 'IP_AUTOMATED_BED',
        'IP_AUTOMATED_OTHER_CHARGE', 'REPORTS', 'PATIENT_SEARCH', 'SETTINGS_REFERRAL',
        'SETTINGS_RESULTTEMPLATE', 'SETTINGS_TIMESLOTS', 'SETTINGS_BULKUPLOAD',
        'SETTINGS_DATAQUERY', 'PATIENT_EDIT', 'SETTINGS_CONSULTANT_REVENUESHARE',
        'SETTINGS_PRINTTEMPLATE', 'SETTINGS_MESSAGETEMPLATE', 'SETTINGS_TEMPLATE',
        'PATIENT_PROFILE', 'REPORTS_DIAGNOSTICS', 'REPORTS_BILLS', 'REPORTS_COLLECTIONS',
        'REPORTS_PATIENTS', 'REPORTS_ACCOUNTS', 'REPORTS_REVENUE', 'APPOINTMENT_BOOK',
        'REPORTS_INPATIENT', 'CHECKIN', 'UNBILLED_DIAGNOSTIC_ORDERS', 'TALLY_REPORTS',
        'STOCK_CONSUMPTION', 'REPORTS_PURCHASE', 'REPORTS_STOCK', 'REPORTS_INVENTORY_ANALYSIS',
        'SETTINGS_USER_CONFIGURATION', 'PATIENT_PRINT', 'UPDATE_CLINICAL_TRAIL',
        'SETTINGS_CONFIG', 'SETTINGS_PRESET', 'REPORTS_CLINICAL_ANALYTICS',
        'PATIENT_ALLERGY', 'REPORTS_SALES', 'STOCK_ISSUE', 'STOCK_RETURN',
        'REPORTS_MRD', 'REPORTS_INSURANCE', 'DISCHARGE_SUMMARY_ONLY', 'OP_PACKAGE',
        'DONORS', 'TRANSFUSION', 'BLOOD_BANK', 'SETTINGS_INSTRUMENT',
        'SETTNGS_INSTRUMENTSET', 'REPORTS_EQUIPMENT', 'SETTINGS_ADDITIONAL_INFO_TEMPLATE',
        'ATTACHMENT', 'PURCHASE_REQUEST', 'REFERRAL', 'REPORT_APPOINTMENT',
        'REPORT_PATIENT', 'STOCK', 'SALES'
    )
);

DELETE FROM features WHERE feature_key IN (
    -- First list of 18 deleted permission keys
    'SETTINGS_SMS_TEMPLATE', 'SETTINGS_UOM', 'SETTINGS_AREA', 'SETTINGS_ACCOUNTUNIT',
    'REPORTS_OT', 'SETTINGS_VEHICLE', 'REPORTS_CSSD', 'CSSD', 'REPORTS_AMBULANCE',
    'SETTINGS_EQUIPMENT', 'AMBULANCE', 'SETTINGS_MOLECULE', 'BLOOD_STOCK',
    'DONOR_BLEEDING', 'IP_PACKAGE', 'REPORTS_BLOOD_BANK', 'STOCK_INDENT',
    'SETTINGS_OPERATION_THEATER',

    -- Second list of duplicate and obsolete permission keys
    'PATIENT_BILLS', 'PAYMENT', 'SPECIAL_COLLECTION', 'IP_AUTOMATED_BED',
    'IP_AUTOMATED_OTHER_CHARGE', 'REPORTS', 'PATIENT_SEARCH', 'SETTINGS_REFERRAL',
    'SETTINGS_RESULTTEMPLATE', 'SETTINGS_TIMESLOTS', 'SETTINGS_BULKUPLOAD',
    'SETTINGS_DATAQUERY', 'PATIENT_EDIT', 'SETTINGS_CONSULTANT_REVENUESHARE',
    'SETTINGS_PRINTTEMPLATE', 'SETTINGS_MESSAGETEMPLATE', 'SETTINGS_TEMPLATE',
    'PATIENT_PROFILE', 'REPORTS_DIAGNOSTICS', 'REPORTS_BILLS', 'REPORTS_COLLECTIONS',
    'REPORTS_PATIENTS', 'REPORTS_ACCOUNTS', 'REPORTS_REVENUE', 'APPOINTMENT_BOOK',
    'REPORTS_INPATIENT', 'CHECKIN', 'UNBILLED_DIAGNOSTIC_ORDERS', 'TALLY_REPORTS',
    'STOCK_CONSUMPTION', 'REPORTS_PURCHASE', 'REPORTS_STOCK', 'REPORTS_INVENTORY_ANALYSIS',
    'SETTINGS_USER_CONFIGURATION', 'PATIENT_PRINT', 'UPDATE_CLINICAL_TRAIL',
    'SETTINGS_CONFIG', 'SETTINGS_PRESET', 'REPORTS_CLINICAL_ANALYTICS',
    'PATIENT_ALLERGY', 'REPORTS_SALES', 'STOCK_ISSUE', 'STOCK_RETURN',
    'REPORTS_MRD', 'REPORTS_INSURANCE', 'DISCHARGE_SUMMARY_ONLY', 'OP_PACKAGE',
    'DONORS', 'TRANSFUSION', 'BLOOD_BANK', 'SETTINGS_INSTRUMENT',
    'SETTNGS_INSTRUMENTSET', 'REPORTS_EQUIPMENT', 'SETTINGS_ADDITIONAL_INFO_TEMPLATE',
    'ATTACHMENT', 'PURCHASE_REQUEST', 'REFERRAL', 'REPORT_APPOINTMENT',
    'REPORT_PATIENT', 'STOCK', 'SALES'
);
