-- V173__update_lab_print_template_minimal.sql

DO $$
DECLARE
    t_lab TEXT;
BEGIN
    t_lab := $T$<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=DM+Mono:wght@400;500&display=swap');
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'DM Sans',sans-serif;font-size:10px;color:#111827;background:#fff}
.page{padding:14mm 12mm 10mm;min-height:273mm;display:flex;flex-direction:column}
.header-table{width:100%;border-collapse:collapse;margin-bottom:15px;border-bottom:2px solid #2563eb}
.header-table td{padding:6px 0;vertical-align:middle;border:none}
.logo-td{width:70px;padding-right:12px;vertical-align:middle;border:none}
.logo-img{max-height:48px;max-width:70px;display:block;object-fit:contain}
.h-name{font-size:16px;font-weight:700;text-transform:uppercase;color:#1e3a8a;letter-spacing:0.5px}
.h-sub{font-size:8.5px;color:#4b5563;line-height:1.4;margin-top:3px}
.report-title-cell{text-align:right;width:200px}
.report-title{font-size:15px;font-weight:700;color:#2563eb;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px}
.report-meta{font-family:'DM Mono',monospace;font-size:8.5px;color:#4b5563;margin-top:1px}
.patient-details{width:100%;margin:15px 0;border-collapse:collapse}
.patient-details td{padding:4px 0;font-size:10px;color:#111827;vertical-align:top;border:none}
.results-table{width:100%;border-collapse:collapse;margin:20px 0}
.results-table thead{background:#eff6ff;border-top:1.5px solid #3b82f6;border-bottom:1.5px solid #3b82f6}
.results-table th{font-size:10px;font-weight:700;color:#1e3a8a;padding:8px 6px;text-align:left}
.results-table th.c{text-align:center}
.results-table tbody tr{border-bottom:1px solid #e2e8f0}
.results-table tbody td{padding:8px 6px;font-size:10px;vertical-align:middle}
.results-table td.val{text-align:center;font-family:'DM Mono',monospace;font-weight:600;font-size:10px;color:#111827}
.results-table td.unit{text-align:center;font-family:'DM Mono',monospace;color:#4b5563;font-size:9.5px}
.results-table td.range{text-align:center;color:#4b5563;font-size:9.5px}
/* Override inline styles generated by buildResultLinesHtml to match CharmHealth minimal look */
.results-table tbody td[style*="background-color"]{background-color:#f8fafc !important;color:#1e3a8a !important;border-bottom:1px solid #bfdbfe !important;padding:6px 6px !important}
.results-table tbody td[style*="text-decoration:underline"]{color:#2563eb !important;padding-top:14px !important;padding-bottom:4px !important;text-decoration:none !important;border-bottom:2px solid #3b82f6 !important}
.end-report{text-align:center;margin:25px 0 10px;font-size:9px;color:#4b5563;font-weight:bold;letter-spacing:1px}
.footer{margin-top:auto;padding-top:8px;border-top:1px solid #e5e7eb;display:flex;justify-content:space-between;align-items:flex-end}
.fn{font-size:7.5px;color:#6b7280;line-height:1.4}
.sig{text-align:center;font-size:8.5px}
.sig-line{border-top:1px solid #d1d5db;width:120px;margin:0 auto;padding-top:3px;color:#374151;font-weight:600}
@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style></head>
<body><div class="page">
  <table class="header-table">
    <tr>
      <td class="logo-td">
        <img class="logo-img" src="#{profile.logoDataUrl}" onerror="this.parentNode.style.display='none'" />
      </td>
      <td>
        <div class="h-name">#{profile.name}</div>
        <div class="h-sub">#{profile.address} <br/> #{profile.contactNo}</div>
      </td>
      <td class="report-title-cell">
        <div class="report-title">Lab Report</div>
        <div class="report-meta">Ref No: #{data.sequenceNumber}</div>
        <div class="report-meta">Date: #{data.orderDate}</div>
      </td>
    </tr>
  </table>
  <table class="patient-details">
    <tr>
      <td style="width:15%;font-weight:bold;color:#4b5563">Name</td>
      <td style="width:40%">: #{data.patientName}</td>
      <td style="width:15%;font-weight:bold;color:#4b5563">Age / Sex</td>
      <td style="width:30%">: #{data.patientAge} / #{data.patientGender}</td>
    </tr>
    <tr>
      <td style="font-weight:bold;color:#4b5563">PID No</td>
      <td>: #{data.patientNumber}</td>
      <td style="font-weight:bold;color:#4b5563">Ref.No</td>
      <td>: #{data.sequenceNumber}</td>
    </tr>
    <tr>
      <td style="font-weight:bold;color:#4b5563">Bill.No</td>
      <td>: #{data.sequenceNumber}</td>
      <td style="font-weight:bold;color:#4b5563">Date</td>
      <td>: #{data.orderDate}</td>
    </tr>
    <tr>
      <td style="font-weight:bold;color:#4b5563">Ref.By</td>
      <td>: #{data.consultantName}</td>
      <td></td>
      <td></td>
    </tr>
  </table>
  <table class="results-table">
    <thead>
      <tr class="headers-row">
        <th style="width:35%">Investigations</th>
        <th style="width:15%;text-align:center">Results</th>
        <th style="width:15%;text-align:center">Unit</th>
        <th style="width:35%;text-align:center">Biological Reference Interval</th>
      </tr>
    </thead>
    <tbody>
      #{data.resultLines}
    </tbody>
  </table>
  <div class="end-report">--End of report--</div>
  <div class="footer">
    <div class="fn">
      <div>Queries: #{profile.contactNo}</div>
      <div>* H=High L=Low N=Normal &nbsp;|&nbsp; Report valid 30 days</div>
    </div>
    <div class="sig">
      <div class="sig-line">Lab Technician</div>
      <div style="font-size:7.5px;color:#6b7280;margin-top:2px">#{profile.name}</div>
    </div>
  </div>
</div></body></html>$T$;

    UPDATE print_templates 
    SET content = t_lab 
    WHERE document_type = 'LAB';
END $$;
