package com.hms.infrastructure.persistence.nhcx;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public interface NhcxTransactionJpaRepository extends JpaRepository<NhcxTransactionEntity, UUID> {

    /**
     * Look up by correlation id, without a tenant filter.
     *
     * <p>Callbacks arrive with no session and therefore no tenant context. The
     * correlation id was generated by us and is unique, and the payload's
     * signature is verified before this is called, so resolving the tenant from
     * the stored row is sound.
     */
    Optional<NhcxTransactionEntity> findByCorrelationId(String correlationId);

    List<NhcxTransactionEntity> findByStateOrderByCreatedAtDesc(String state);

    /**
     * Claims and pre-auths for the control tower — Screen 5.2.
     *
     * <p>Tenant-scoped by the Hibernate filter like any session-backed query.
     * Ordered newest first because the tower is a work surface, not an archive.
     */
    List<NhcxTransactionEntity> findByExchangeTypeInOrderByCreatedAtDesc(
        List<String> exchangeTypes);

    /** Submissions past their deadline with no payer response. Tenant-agnostic:
     *  the sweep runs on a scheduled thread and must cover every tenant. */
    @Query("SELECT t FROM NhcxTransactionEntity t "
         + "WHERE t.state IN ('SUBMITTED', 'ACKNOWLEDGED') AND t.expiresAt < :cutoff")
    List<NhcxTransactionEntity> findStalled(@Param("cutoff") Instant cutoff);
}
