package com.hms.domain.gst.model;

import com.hms.domain.shared.model.AuditableEntity;
import com.hms.security.encryption.EncryptedStringConverter;
import com.hms.security.encryption.PiiField;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * One attempt at producing a return for one period (A6).
 *
 * <p>The generated payload and any GSP response are both retained on the record. That is
 * the audit trail A7 asks for: a return can be questioned months later, and "what exactly
 * did we send, and what came back" is unanswerable from summary figures alone.
 *
 * <p>Regenerating a period creates a new record rather than overwriting the old one.
 * The figures change as back-dated bills land, and losing the earlier version would
 * erase the evidence of what was filed at the time.
 */
@Entity
@Table(name = "gst_filing_records")
@Getter @Setter @NoArgsConstructor
@org.hibernate.annotations.Filter(name = "tenantFilter", condition = "tenant_id = :tenantId")
public class GstFilingRecord extends AuditableEntity {

    @Enumerated(EnumType.STRING)
    @Column(name = "return_type", nullable = false, length = 20)
    private GstReturnType returnType;

    /** MMYYYY, the form GST returns use for a period. */
    @Column(name = "return_period", nullable = false, length = 6)
    private String returnPeriod;

    @Column(name = "period_start", nullable = false)
    private LocalDate periodStart;

    @Column(name = "period_end", nullable = false)
    private LocalDate periodEnd;

    @Enumerated(EnumType.STRING)
    @Column(name = "filing_status", nullable = false, length = 20)
    private GstFilingStatus filingStatus = GstFilingStatus.DRAFT;

    @Enumerated(EnumType.STRING)
    @Column(name = "environment", nullable = false, length = 20)
    private GstEnvironment environment = GstEnvironment.SANDBOX;

    @PiiField(category = PiiField.PiiCategory.TAX_ID, description = "Filing GSTIN")
    @Convert(converter = EncryptedStringConverter.class)
    @Column(name = "gstin", length = 512)
    private String gstin;

    @Column(name = "payload", columnDefinition = "TEXT")
    private String payload;

    @Column(name = "response_body", columnDefinition = "TEXT")
    private String responseBody;

    /** ARN or GSP reference, once anything has accepted the return. */
    @Column(name = "reference_id", length = 100)
    private String referenceId;

    @Column(name = "total_taxable_value", precision = 16, scale = 2)
    private BigDecimal totalTaxableValue = BigDecimal.ZERO;

    @Column(name = "total_cgst", precision = 16, scale = 2)
    private BigDecimal totalCgst = BigDecimal.ZERO;

    @Column(name = "total_sgst", precision = 16, scale = 2)
    private BigDecimal totalSgst = BigDecimal.ZERO;

    @Column(name = "total_igst", precision = 16, scale = 2)
    private BigDecimal totalIgst = BigDecimal.ZERO;

    @Column(name = "total_cess", precision = 16, scale = 2)
    private BigDecimal totalCess = BigDecimal.ZERO;

    @Column(name = "line_item_count", nullable = false)
    private int lineItemCount = 0;

    @Column(name = "submitted_at")
    private Instant submittedAt;

    /**
     * True when the scheduler produced this rather than a person.
     *
     * <p>The job supersedes its own previous output for a period so a daily run does not
     * leave thirty drafts behind. It must never touch a return somebody generated
     * deliberately, and this flag is the only thing separating the two.
     */
    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated = false;

    /**
     * Lazy: a busy month is thousands of lines, and nothing outside a payload rebuild
     * needs them. Never touch this from a controller — OSIV is disabled.
     */
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @JoinColumn(name = "filing_record_id")
    private List<GstFilingLineItem> lineItems = new ArrayList<>();

    /**
     * Eager, unlike the line items. There are a handful of these at most, and they are
     * the first thing anyone looking at a filing needs to see — a record shown without
     * the reason it failed is useless. With OSIV disabled, lazy would mean either a
     * fetch join on every read path or an exception the first time one is rendered.
     */
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @JoinColumn(name = "filing_record_id")
    private List<GstFilingError> errors = new ArrayList<>();

    public void addLineItem(GstFilingLineItem item) {
        item.setTenantId(getTenantId());
        lineItems.add(item);
    }

    public void addError(GstFilingError error) {
        error.setTenantId(getTenantId());
        errors.add(error);
    }
}
